import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import { loadFonts } from "./plugins/webfontloader";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/antd.css";
loadFonts();
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.use(Antd);
app.mount("#app");
